name: Deploy Admin Dashboard Production
on:
  push:
    branches: [master]
jobs:
  web-deploy:
    name: 🎉 Deploy Production
    runs-on: ubuntu-latest
    env:
      VITE_BASE_URL: https://tedxubproduction.my.id/admin
      VITE_PUBLIC_URL: https://tedxubproduction.my.id
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: 🔨 Build Project
        run: |
          yarn install --frozen-lockfile
          yarn build

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: "./dist/"
          server-dir: "./"
